# Generated by Django 6.0.4 on 2026-05-01 14:38

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='online_wallet',
            field=models.CharField(blank=True, choices=[('JazzCash', 'JazzCash'), ('Easypaisa', 'Easypaisa'), ('NayaPay', 'NayaPay'), ('SadaPay', 'SadaPay')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Online Payment', 'Online Payment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='default', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
