# Generated by Django 5.2.1 on 2026-05-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_manualpaymentmethod_alter_order_online_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='watch_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
