# Generated by Django 6.0.4 on 2026-05-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_watch_watch_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='category',
            field=models.CharField(choices=[('Analog', 'Analog'), ('Digital', 'Digital'), ('Sports', 'Sports')], default='Analog', max_length=20),
        ),
    ]
